services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASS
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env
    networks:
      - mongo_server

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - ./.env
    networks:
      - mongo_server
      - nginx_server
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - frontend:/app/build

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nginx_server
    volumes:
      - frontend:/usr/share/nginx/html
      - ./nginx/default:/etc/nginx/conf.d
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/yphymns.ru/:ro
    depends_on:
      - client
      - server

#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  mongo_server:
    driver: bridge
  nginx_server:
    driver: bridge
volumes:
  mongo_data:
    external: true
  frontend:
    external: true
